model:
    arch: segnet
data:
    dataset: chroma
    train_split: train
    val_split: val
    img_rows: 360
    img_cols: 480
    path: /Users/teresazhao/Desktop/DL-Project/pytorch-semseg/dataset/chroma  
training:
    train_iters: 12
    batch_size: 1
    val_interval: 1000
    n_workers: 0
    print_interval: 1
    optimizer:
        name: 'sgd'
        lr: 1.0e-10
        weight_decay: 0.0005
        momentum: 0.99
    loss:
        name: 'ssim_loss_function'
        size_average: False
    lr_schedule:
    resume: 
