model:
    arch: segnet
data:
    dataset: camvid
    train_split: train
    val_split: val
    img_rows: 360
    img_cols: 480
    path: /Users/LiMeng/Downloads/541Multimedia/Project/pytorch-semseg/dataset/camvid 
training:
    train_iters: 10
    batch_size: 1
    val_interval: 1000
    n_workers: 1
    print_interval: 50
    optimizer:
        name: 'sgd'
        lr: 1.0e-10
        weight_decay: 0.0005
        momentum: 0.99
    loss:
        name: 'cross_entropy'
        size_average: False
    lr_schedule:
    resume: 
