model:
    arch: segnet
data:
    dataset: chroma
    train_split: train
    val_split: val
    img_rows: 360
    img_cols: 480
    path: ./dataset/chroma 
training:
    train_iters: 9000
    batch_size: 1
    val_interval: 1000
    n_workers: 0
    print_interval: 2
    optimizer:
        name: 'adam'
        lr: 1.0e-3
        weight_decay: 0.0005
        #momentum: 0.99
    loss:
        name: 'chrom_downsampling_loss'
        size_average: False
    lr_schedule:
    resume: 
